Added Font Awesome
photion/web-admin pull request #126
Opened 2020-10-01 18:11 UTC by birimbau

As an example on how to use font awesome icons I left the icon faUserSecret imported already (However might not be needed).
Let me know if that code should be commented.

2020-10-01 21:27 UTC, dipasqualew requested changes
Thank you, great stuff! I left a couple of notes and a question whether we need a Vue wrapper for FontAwesome. Let me know your thoughts 🙂

2020-10-01 21:27 UTC, dipasqualew commented on .envrc.example.sh
> -# Rename this file as .envrc
I think this file has been deleted by mistake? It should be brought back 🙂

2020-10-01 21:27 UTC, dipasqualew commented on package.json
> +    "@fortawesome/vue-fontawesome": "2",
Do we strictly need vue components for the icons? My preference would be to solve the issue with pure css - this way we have more flexibility on how we combine the icons with the components and the site is both faster to load and faster to transition.

Only reason I can see having the components is having a "type" for the icon (i.e. you can use the wrong css class on a component and not notice errors).

2020-10-01 21:27 UTC, dipasqualew commented on src/plugins/font-awesome.ts
> +library.add(faUserSecret);
Thank you for adding an example, so I can just copy paste my way through a solution 😄 However, I think it would be better to comment out this line and the one below with a small comment on top explaining "This is how you can add an icon"

2020-10-03 15:24 UTC, birimbau commented on .envrc.example.sh
> -# Rename this file as .envrc
Recovered the file

2020-10-03 15:25 UTC, birimbau commented on src/plugins/font-awesome.ts
> +library.add(faUserSecret);
Added the comments on how to use Font Awesome

2020-10-03 15:30 UTC, birimbau commented on package.json
> +    "@fortawesome/vue-fontawesome": "2",
After some thought I have to agree you on this. Leaving the implementation of Font Awesome as simple as possible will make it easier to integrate in order components that might use icons. 
In order to make it simple

2020-10-03 15:35 UTC, dipasqualew commented on src/plugins/font-awesome.ts
> +library.add(faUserSecret);
Cool, thanks!

2020-10-03 15:36 UTC, dipasqualew commented on package.json
> +    "@fortawesome/vue-fontawesome": "2",
Simplicity reigns 😄

2020-10-03 16:49 UTC, dipasqualew approved these changes
Thank you very much! Glad that warning got removed 😄

2020-10-03 16:58 UTC, merged